COMMON: &common
  FLASK_APP: "glider_dac:create_app()"
  HOST: localhost
  PORT: 5000
  DEBUG: False
  MONGODB_HOST: mongo
  MONGODB_PORT: 27017
  MONGODB_DATABASE: gliderdac

  APPLICATION_PREFIX: "/gliders/"
  SECRET_KEY: thisisakey
  LOG_FILE: yes
  WEB_PASSWORD: password

  MAIL_ENABLED: False
  MAIL_SERVER: smtp-server
  #MAIL_SERVER: localhost
  MAIL_PORT: 25
  #MAIL_PORT: 2525
  MAIL_USERNAME: mail-username
  MAIL_PASSWORD: mail-password
  MAIL_USE_TLS: True
  MAIL_DEFAULT_SENDER: sender@domain.com
  # Must be numeric to operate properly?
  #MAILER_DEBUG: True
  MAILER_DEBUG: 1
  MAIL_DEFAULT_TO: receiver@domain.com
  #MAIL_DEFAULT_LIST: YOUR_EMAIL
  #
  
  # IMPORTANT: Modification tracking must be set to True for certain parts of
  # deployment lifecyle to work properly!
  SQLALCHEMY_TRACK_MODIFICATIONS: True

  # Google Analytics
  GA_ENABLED: True
  GA_TAG_ID: G-999999AAAA

  PRIVATE_ERDDAP: erddap:8080
  PUBLIC_ERDDAP: erddap:8080
  THREDDS: gliders.ioos.us
  DATA_ROOT: /data/submission
  PRIV_DATA_ROOT: /data/data/priv_erddap
  PUBLIC_DATA_ROOT: /data/data/pub_erddap
  THREDDS_DATA_ROOT: /data/data/thredds
  ARCHIVE_PATH: data/ftp/archive
  DEV_CATALOG_ROOT: PATH_TO_CODE_ROOT/tds_catalogs
  INFLUXDB_HOST: 127.0.0.1
  INFLUXDB_PORT: 8086
  ADMINS:
   - admin

  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 8
  REDIS_URL: redis://redis:6379/8
  SESSION_PERMANENT: True
  SESSION_TYPE: redis

  JSON_DIR: '/data/data/priv_erddap/'
  path2priv: '/data/data/priv_erddap/'
  path2pub: '/data/data/pub_erddap/'
  path2thredds: '/data/data/thredds/'
  flags_private: '/scratch/tomcat-erddap-private/flag'
  flags_public: '/scratch/tomcat-erddap-public/flag'
  SERVER: "http://localhost:8080/erddap"
  erddap_private: 'localhost:8080'
  erddap_public: 'localhost:8081'
  AWS_ACCESS_KEY_ID: 'xxxxxxxxxxxxxxxxxxxx'
  AWS_SECRET_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  BUCKET_NAME: 'ioosngdac'
  NCEI_DIR: "/data/data/archive"
  API_URL: 'http://data.ioos.us/gliders/providers/api/deployment'
  PUBLIC_CATALOG: '/data/catalog/pub_erddap/datasets.xml'
  PRIVATE_CATALOG: '/data/catalog/priv_erddap/datasets.xml'

  SQLALCHEMY_DATABASE_URI: mysql://username:password@mysql/gliderdac

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

TESTING:
  <<: *common
  DEBUG: True
  TESTING: True
