[project]
authors = ["Glider DAC Team"]
channels = ["conda-forge"]
description = "The IOOS Glider DAC site/scripts/tools"
name = "glider-dac"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "2.0"

[tasks]

[dependencies]
python = "3.13.*"
aiofiles = "==24.1.0"
aiohttp = "==3.11.9"
async-timeout = "<5.0"
awscli = ">=1.38.22,<2"
cc-plugin-glider = ">=2.0.3"
cf-units = ">=2.1.5"
cftime = "==1.6.4"
compliance-checker = ">=5.0.0"
feedparser = "==6.0.1"
flasgger = "==0.9.7.1"
flask-cors = "==5.0.0"
flask-login = ">=0.5.0"
flask-mail = "==0.9.1"
flask-script = ">=2.0.6,<3"
flask-session = ">=0.8.0,<0.9"
flask-sqlalchemy = ">=2.5.1"
flask-wtf = ">=1.0.1"
flask = "<2.4"
geoalchemy2 = ">=0.11.1"
geojson = ">=3.2.0,<4"
gunicorn = ">=20.1.0"
influxdb = ">=5.3.1"
ioos-qc = "==2.2.0"
lxml = ">=5.3.1,<6"
marshmallow = ">=3.26.1,<4"
marshmallow-sqlalchemy = ">=1.4.1,<2"
multidict = ">=6.2.0,<7"
mysqlclient = ">=2.2.7,<3"
netcdf4 = ">=1.5.8"
passlib = ">=1.7.4"
pyyaml = ">=6.0"
quantities = "==0.14.1"
redis-py = ">=5.2.1,<6"
requests = ">=2.20.1"
rq = ">=2.2.0,<3"
simplekv = ">=0.14.1,<0.15"
thredds_crawler = ">=1.5.4"
watchdog = ">=0.9.0"
werkzeug = ">=3.0.6"
sh = ">=2.2.2,<3"
