#!/bin/sh

# ./sync_cmd <ssh user> <remote host> <src> <dest>

# loops through all users on remote host (aka top level dirs in /data/ftp)
# and executes one rsync command per each in order to chop off the upload/
# part of the path.

users=($(ssh -l $1 $2 ls $3))

for i in "${users[@]}"
do
    rsync -r -a -v --delete -e "ssh -l $1" $2:$3/$i/upload/ $4/$i
done


