database = gliderdac
user = glider
host = localhost
password = CHANGEME
table = "user"

user_column = username
pwd_column = password
#expired_column = acc_expired
#newtok_column = acc_new_pwreq
pw_type = crypt
debug = 1
