# Example minimal vsftpd config with virtual users
# adapt as needed
listen=YES
listen_ipv6=YES

anonymous_enable=NO
local_enable=YES
write_enable=YES

pam_service_name=vsftpd

# This section gives an example TLS configuration in a commented form.
# It is highly recommended to adapt this section to TLS certificates
# you control for production usage
#
#ssl_enable=YES
#rsa_cert_file=/etc/ssl/private/vsftpd.pem
#rsa_private_key_file=/etc/ssl/private/vsftpd.pem

# # Force SSL for all local users
# force_local_data_ssl=YES
# force_local_logins_ssl=YES
#
# # Optional: Force SSL for anonymous users
# allow_anon_ssl=YES
# force_anon_data_ssl=YES
# force_anon_logins_ssl=YES
#
# # Protocol versions (prefer TLS)
# ssl_tlsv1=YES
# ssl_tlsv1_1=YES
# ssl_tlsv1_2=YES
# ssl_sslv2=NO
# ssl_sslv3=NO
#
# # Strong ciphers
# ssl_ciphers=HIGH

guest_enable=YES
guest_username=ftp
virtual_use_local_privs=YES

user_sub_token=$USER
local_root=/data/data/priv_erddap/$USER

chroot_local_user=YES
allow_writeable_chroot=YES

session_support=YES
xferlog_enable=YES
