name: User Request
description: Submit a user request to the IOOS GDAC
title: "User Request: "
labels: ["User Request"]
projects: ["ioos/6"]
body:
  - type: markdown
    attributes:
      value: To submit a user request to the IOOS Glider Data Assembly Center, please fill out the issue template below.
  - type: input
    id: who
    attributes:
      label: Who is requesting this?
  - type: textarea
    id: what
    attributes:
      label: What is being requested?
  - type: textarea
    id: why
    attributes:
      label: How would this request improve your current workflow?
  - type: textarea
    id: alt
    attributes:
      label: Any alternative approaches or workarounds?
  - type: input
    id: contact
    attributes:
      label: How can we get in contact with you to follow up on this request?
