"""Enable Flask-Security

Revision ID: d9666941cb2b
Revises:
Create Date: 2026-02-24 18:25:15.899778

"""

from alembic import op
import sqlalchemy as sa

import flask_security
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = "d9666941cb2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("us_phone_number", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("us_totp_secrets", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("fs_uniquifier", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(sa.Column("confirmed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("current_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("last_login_ip", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("current_login_ip", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("login_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("tf_primary_method", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tf_totp_secret", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tf_phone_number", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "create_datetime",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "update_datetime",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        # Generate unique values for existing rows
        # End batch operation before running UPDATE
    conn = op.get_bind()
    conn.execute(
        text("""
        UPDATE `user`
        SET fs_uniquifier = UUID()
        WHERE fs_uniquifier IS NULL OR fs_uniquifier = ''
    """)
    )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["us_phone_number"])
        batch_op.create_unique_constraint(None, ["fs_webauthn_user_handle"])
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("update_datetime")
        batch_op.drop_column("create_datetime")
        batch_op.drop_column("tf_phone_number")
        batch_op.drop_column("tf_totp_secret")
        batch_op.drop_column("tf_primary_method")
        batch_op.drop_column("login_count")
        batch_op.drop_column("current_login_ip")
        batch_op.drop_column("last_login_ip")
        batch_op.drop_column("current_login_at")
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("confirmed_at")
        batch_op.drop_column("fs_uniquifier")
        batch_op.drop_column("active")
        batch_op.drop_column("us_totp_secrets")
        batch_op.drop_column("us_phone_number")
        batch_op.drop_column("mf_recovery_codes")
        batch_op.drop_column("fs_webauthn_user_handle")

    # ### end Alembic commands ###
