# Configure Variables
JSON_DIR              = '/data/data/priv_erddap/'
path2priv             = '/data/data/priv_erddap/'
path2pub              = '/data/data/pub_erddap/'
path2thredds          = '/data/data/thredds/'
flags_private         = '/scratch/tomcat-erddap-private/flag'
flags_public          = '/scratch/tomcat-erddap-public/flag'
SERVER                = "http://localhost:8080/erddap"
erddap_private        = 'localhost:8080'
erddap_public         = 'data.ioos.us/gliders'
AWS_ACCESS_KEY_ID     = 'xxxxxxxxxxxxxxxxxxxx'
AWS_SECRET_ACCESS_KEY = 'xxxxxxxxxxxxxxxxxxxx'
BUCKET_NAME           = 'xxxxxxxxxxxxxxxxxxxxxx'
NCEI_DIR              = "/tmp/ncei"
API_URL               = 'http://data.ioos.us/gliders/providers/api/deployment'
