# Configure Variables
JSON_DIR              = '/tmp/priv_erddap/'
path2priv             = '/tmp/priv_erddap/'
path2pub              = '/tmp/pub_erddap/'
path2thredds          = '/tmp/thredds/'
flags_private         = '/tmp/erddap-gdac/flag'
flags_public          = '/tmp/erddap/flag'
SERVER                = "http://localhost:9080/erddap"
erddap_private        = 'localhost:9080'
erddap_public         = 'localhost:8080'
AWS_ACCESS_KEY_ID     = 'xxxxxxxxxxxxxxxxxxxx'
AWS_SECRET_ACCESS_KEY = 'xxxxxxxxxxxxxxxxxxxx'
BUCKET_NAME           = 'xxxxxxxxxxxxxxxxxxxxxx'
NCEI_DIR              = "/tmp/ncei"
API_URL               = 'http://localhost:3000/api/deployment'
PUBLIC_CATALOG        = '/tmp/catalog/pub_erddap/datasets.xml'
PRIVATE_CATALOG       = '/tmp/catalog/priv_erddap/datasets.xml'
