name: Check Markdown links

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches:
      - gh-pages

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3.0.0
      with:
        files: "_docs"

    - name: Check links
      if: steps.check_files.outputs.files_exists == 'true'
      uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31  # v1.0.17
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'
        file-path: './README.md'
        folder-path: '_docs/'
