name: Run pytest

# no permissions by default
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Start Redis
        uses: supercharge/redis-github-action@bc274cb7238cd63a45029db04ee48c07a72609fd # v1.8.1
        with:
          redis-version: 7

      - name: Build Docker image
        run: docker build -t glider-dac-build .

      - name: Install testing requirements and run tests
        # FIXME: Why is it necessary to set FLASK_ENV to TESTING here when
        # pytest runs off GHA usually set this properly?
        run: >
          docker run --network host -e FLASK_ENV=TEST_CONFIG
          -e OVERRIDE_REDIS_HOST=localhost -e OVERRIDE_REDIS_URL=redis://localhost:6379/8
          --rm -u root glider-dac-build bash -c
          "pip install --no-cache -r /glider-dac/test_requirements.txt &&
           pytest /glider-dac/glider_dac/tests"
