name: Run pytest

# no permissions by default
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t glider-dac-build .

      - name: Run tests
        run: docker run --rm glider-dac-build pytest /glider-dac/tests
