name: Run pytest

# no permissions by default
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t glider-dac-build .

      - name: Run tests
        run: docker run --rm glider-dac-build pytest /glider-dac/tests
